### ISSUE TITLE
Fix Button

### ISSUE THREAD

**Issue by mmcpal** [mmcpal/learning-git#3]
gawin nyo to

**Comment by mmcpal** [comment]
Kamusta kayo dyannn @nt-test @eycpal

**Comment by mmcpal** [comment]
update na ba yun notification settings mo @eycpal

**Comment by nt-test** [comment]
congratulations on getting notified, @eycpal and @mmcpal !!! ✨

**Comment by eycpal** [comment]
Yehey!!!

**Comment by mmcpal** [comment]
> congratulations on getting notified, @eycpal and @mmcpal !!! ✨

Thank you! haha
